### ISSUE TITLE
Empty email when opening K9-Mail (occasionally)

### ISSUE THREAD

**Issue by martin-ueding** [thunderbird/thunderbird-android#1185]
### Expected behaviour

When I open K9-Mail, it should display the last message or some folder.
### Actual behaviour

Sometimes I am prompted with an empty email, like this:

![k9-mail](https://cloud.githubusercontent.com/assets/976924/13845287/518cb7e8-ec3f-11e5-9d4b-cab7f27139fd.png)

The date shown is clearly the zero of timestamp in UTC+1. The subject line is `(No subject)` and the text says `no body text`.
### Steps to reproduce

I am not really sure, I think it happens when I open K9-Mail after a long time. Perhaps the garbage collector has moved some stuff out of the way?
### Environment

K-9 Mail version: 5.008
Android version: 5.0.2
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by 0xf10e** [comment]
I haven't k9 configured to show the last mail on start-up but I know how to reproduce:
When you synchronize you messages and a mail's subject _but not its content's preview_ is shown open the mail.
Now you got an empty "(No subject)" mail you can't get rid of on this client.

I think I actually knew a way to get rid of the empty mail but I've forgotten how to do it :(

**Comment by 0xf10e** [comment]
BTW: I've seen this behavior for quite some time (a year?) now.

**Comment by philipwhiuk** [comment]
That one sounds like a message synchronization bug @0xf10e , separate to @martin-ueding 's bug relating to GC or something.

**Comment by 0xf10e** [comment]
I would make an uninformed guess and say my message synchronization bug is the underlying cause of his bug ;)
If you want I can open a new issue.

**Comment by philipwhiuk** [comment]
Hmm maybe. I guess we can always try and reproduce his issue once we've fixed the outstanding issues with sync.

**Comment by martin-ueding** [comment]
I have an idea: perhaps it occurs when I leave displaying an email and delete that email using another client. Then the app still wants to show that email, but it has vanished on the server. I can try to reproduce that when I am home.
-- 
http://martin-ueding.de/#pk_campaign=Email

Sent from my mobile, please excuse my brevity.

**Comment by benebun** [comment]
Have the same issue, occurs when I open an email while its folder is still syncing.
Sometimes returning to the list fixes it sometimes not and the email content can't be displayed anymore.
Header only shows: Message-ID: [ID]@email.android.com
Is there a workaround to resync this mail or folder?

**Comment by Iviabc** [comment]
I am using k9-mail since many years with no problems at all, and I like it vm. 
Since last updates I cannot see the content of the messages, even if I regularly receive the emails

**Comment by Iviabc** [comment]
I tried to Uninstaller and start all over again. Not solved the problem. I have  Huawei mate 19 pro.

**Comment by cketti** [comment]
Steps to reproduce:
1. Enable "Don't keep activities" in Android's developer settings
2. Open a message in K-9 Mail
3. Delete the message from the server
4. Wait for K-9 Mail to sync that change (either through periodic polling or push)
5. Switch to another app
6. Switch back to K-9 Mail ⇒ empty message view screen is displayed

We currently don't update the message view screen when the state of the displayed message was changed on the server, e.g. when the read state was changed by another app. We should listen to changes to the message and update the view accordingly. When the message was deleted, we should return to the message list.

**Comment by cketti** [comment]
The app now automatically closes the message view when the message has been removed.
