### ISSUE TITLE
Lists in emails are not displayed properly

### ISSUE THREAD

**Issue by thelexon** [thunderbird/thunderbird-android#2015]
### Expected behavior
After the last update some emails no longer show the contents of the lists.
The emails come from outlook 2010 client.

### Actual behavior
On k9:
![image](https://cloud.githubusercontent.com/assets/24956557/21750197/ed66f61c-d5ad-11e6-9313-0843687a91a7.png)

on outlook:
![image](https://cloud.githubusercontent.com/assets/24956557/21750240/22a58a36-d5af-11e6-8456-e5eef4e4360a.png)

### Environment
K-9 Mail version:
5.202
Android version:
nexus 5 - 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by philipwhiuk** [comment]
I tried sending a list to myself via Outlook 365 and it was fine. Do you have the raw message source of that email you could send me / post in this issue? (NB: attachments sent to GitHub are dropped)

**Comment by elhennig** [comment]
Hi I just noticed that problem with v5.202, too.
I was missing some messages from different senders: One qas from Amazon Payments, some others sent by my Fritzbox answering machine. Funny thing is, that the messages are shown once I searched on the server for them.

What I also noticed is the some messages appear on the top of the list after cleaning local messages even if they were received longer ago.

**Comment by philipwhiuk** [comment]
That's a separate issue @elhennig - see #1881

Let's stick to working out why lists in emails might not be being displayed here please.

**Comment by elhennig** [comment]
Thanks for pointing to the correct issue for the date sorting problem...

**Comment by thelexon** [comment]
The emails are created with Outlook 2010 (for clarity)
This is the html extracted from outlook 2010:

`<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns:m="http://schemas.microsoft.com/office/2004/12/omml" xmlns="http://www.w3.org/TR/REC-html40"><head><meta http-equiv=Content-Type content="text/html; charset=iso-8859-1"><meta name=Generator content="Microsoft Word 14 (filtered medium)"><style></style></head><body lang=IT link=blue vlink=purple><div class=WordSection1><p class=MsoNormal><o:p>&nbsp;</o:p></p><p class=MsoNormal>Risultato Monitoraggio:<o:p></o:p></p><p class=MsoNormal><span style='color:#1F497D'><o:p>&nbsp;</o:p></span></p><p class=MsoListParagraph style='text-indent:-18.0pt;mso-list:l0 level1 lfo2'><![if !supportLists]><span style='mso-list:Ignore'>-<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><![endif]>Agenzie Web&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ok<o:p></o:p></p><p class=MsoListParagraph style='text-indent:-18.0pt;mso-list:l0 level1 lfo2'><![if !supportLists]><span style='mso-list:Ignore'>-<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><![endif]>Blogs(Grillo, Dagospia)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ok<o:p></o:p></p><p class=MsoListParagraph style='text-indent:-18.0pt;mso-list:l0 level1 lfo2'><![if !supportLists]><span style='mso-list:Ignore'>-<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><![endif]>Fonti Estere &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ok<o:p></o:p></p><p class=MsoListParagraph style='text-indent:-18.0pt;mso-list:l0 level1 lfo2'><![if !supportLists]><span style='mso-list:Ignore'>-<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><![endif]>Fonti Audio Video&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Corriere TV a 0, in attesa risposta<o:p></o:p></p><p class=MsoListParagraph style='text-indent:-18.0pt;mso-list:l0 level1 lfo2'><![if !supportLists]><span style='mso-list:Ignore'>-<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><![endif]>Fonti Web Prioritarie&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;medicinalive a 0, geopolitica alcune notizie non vengono prese <o:p></o:p></p><p class=MsoListParagraph style='text-indent:-18.0pt;mso-list:l0 level1 lfo2'><![if !supportLists]><span style='mso-list:Ignore'>-<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><![endif]>Quotidiani (Siti)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ok<o:p></o:p></p><p class=MsoListParagraph style='text-indent:-18.0pt;mso-list:l0 level1 lfo2'><![if !supportLists]><span style='mso-list:Ignore'>-<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><![endif]>Quotidiani&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Le Figaro TXT a 0 (così anche su sito),<o:p></o:p></p><p class=MsoListParagraph style='text-indent:-18.0pt;mso-list:l0 level1 lfo2'><![if !supportLists]><span style='mso-list:Ignore'>-<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><![endif]>Piattaforme(+Agenzie,+Twitter)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ok<o:p></o:p></p><p class=MsoListParagraph style='text-indent:-18.0pt;mso-list:l0 level1 lfo2'><![if !supportLists]><span style='mso-list:Ignore'>-<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><![endif]>DB&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;ok<o:p></o:p></p><p class=MsoNormal><span style='color:#1F497D'><o:p>&nbsp;</o:p></span></p><p class=MsoNormal>Buona serata!<span style='color:#1F497D'><o:p></o:p></span></p><p class=MsoNormal><b><span style='font-size:7.5pt;font-family:"Verdana","sans-serif";color:navy;mso-fareast-language:IT'>xxxxxx<o:p></o:p></span></b></p><p class=MsoNormal><i><span style='font-size:7.5pt;font-family:"Verdana","sans-serif";color:navy;mso-fareast-language:IT'>xxxxxx </span></i><i><span style='font-size:7.5pt;font-family:"Verdana","sans-serif";color:#1F497D;mso-fareast-language:IT'><o:p></o:p></span></i></p><p class=MsoNormal><b><span style='color:#1F497D;mso-fareast-language:IT'><o:p>&nbsp;</o:p></span></b></p><p class=MsoNormal><b><span style='font-size:7.5pt;font-family:"Verdana","sans-serif";color:navy;mso-fareast-language:IT'>xxxxxx (</span></b><b><u><span lang=EN-GB style='font-size:7.5pt;font-family:"Verdana","sans-serif";color:blue;mso-fareast-language:IT'><a href="mailto:xxxxx"><span lang=IT>xxxxxx</span></a></span></u></b><b><span style='font-size:7.5pt;font-family:"Verdana","sans-serif";color:navy;mso-fareast-language:IT'>&nbsp; -&nbsp; </span></b><b><u><span lang=EN-GB style='font-size:7.5pt;font-family:"Verdana","sans-serif";color:blue;mso-fareast-language:IT'><a href="xxxx"><span lang=IT>xxxxx</span></a></span></u></b><b><span style='font-size:7.5pt;font-family:"Verdana","sans-serif";color:navy;mso-fareast-language:IT'>)<br></span></b><span style='font-size:7.5pt;font-family:"Verdana","sans-serif";color:navy;mso-fareast-language:IT'>xxxxxxx<o:p></o:p></span></p><p class=MsoNormal><span style='font-size:7.5pt;font-family:"Verdana","sans-serif";color:navy;mso-fareast-language:IT'>xxxxxxxx<o:p></o:p></span></p><p class=MsoNormal><b><span style='font-size:7.5pt;font-family:"Verdana","sans-serif";color:navy;mso-fareast-language:IT'><o:p>&nbsp;</o:p></span></b></p><p class=MsoNormal><b><span style='font-size:7.5pt;font-family:"Verdana","sans-serif";color:navy;mso-fareast-language:IT'>xxxxxx<o:p></o:p></span></b></p><p class=MsoNormal><b><u><span lang=EN-GB style='font-size:7.5pt;font-family:"Verdana","sans-serif";color:blue;mso-fareast-language:IT'><a href="mailto:xxxxx"><span lang=IT>xxxxx</span></a></span></u></b><b><span style='font-size:7.5pt;font-family:"Verdana","sans-serif";color:blue;mso-fareast-language:IT'>&nbsp; <o:p></o:p></span></b></p><p class=MsoNormal><span style='color:#1F497D'><o:p>&nbsp;</o:p></span></p><p class=MsoNormal><span style='color:#1F497D'><o:p>&nbsp;</o:p></span></p></div></body></html>`

**Comment by AdmiralAdama** [comment]
I am also having this issue and I second everything the original poster said.

When viewing e-mails created by Outlook 2010 that contain bulleted lists in K-9 mail, the text disappears.

Space is still created for the text. However it is not selectable.

You can put text in a different color after the original text, and that text is viewable.

I am very frustrated with this issue, and I hope it gets fixed soon.

![screenshot_20170116-165447](https://cloud.githubusercontent.com/assets/25163328/22004081/a2e1ebcc-dc0d-11e6-8025-323a6bade08b.png)

**Comment by philipwhiuk** [comment]
@thelexon Sorry I have been pretty busy. I've managed to reproduce this with your test email. I'll try and look into it and get a patch in for the next bugfix release (5.204)

**Comment by philipwhiuk** [comment]
I suspect this is a HtmlCleaner-related bug like #2148. Long term fix is started by #2159 but we might be able to improve it in the short term.

**Comment by hecsa** [comment]
I understand why #2241 was closed (it's a duplicate), will this one be worked to develop a new K-9 version (today we are using 5.203) to solve this issue?
Thanks a lot, and best regards,

HeCSa.

**Comment by horizon-it-uk** [comment]
Hi,
I have a customer reporting this exact problem after a recent update, is this going to be fixed?
Cheers
Paul

**Comment by thelexon** [comment]
Yes and no... Yes because now the list appears...no because appear like
attachment.


Il 26 mar 2017 23:21, "horizon-it-uk" <notifications@github.com> ha scritto:

**Comment by philipwhiuk** [comment]
Yes we plan to fix it. I've just submitted a PR ( #2447 ) to move from HtmlCleaner (which can't cope with the chaos that Microsoft produce) to Jsoup which looks a lot more promising.

**Comment by psychowood** [comment]
In my case this was more or less fixed in 5.206. More or less meaning that **when reading a message** I see this kind of markup

`<![if !supportLists]>·       <![endif]>1st item
<![if !supportLists]>·       <![endif]>2nd item
            <![if !supportLists]>o   <![endif]>1st indented item
            <![if !supportLists]>o   <![endif]>2nd indented item`

In the Reply view, both with quoted text closed and open (i.e. before and after tapping the pencil icon) the list is shown correctly, bullets included.

**Comment by petersem** [comment]
I am also seeing the "!supportlist" markup when reading emails that originate from Outlook. In my case it is Outlook 2010 and 2013 being read from exchange online o365 on k9.

For example, bullet points in Outlook are replacef with the following text.

<![if !supportLists]>·         <![endif]>Reducing Application Development and Operations Costs
<![if !supportLists]>·         <![endif]>Improving Application Code Quality
<![if !supportLists]>·         <![endif]>Increasing Application Availability

**Comment by philipwhiuk** [comment]
#2447 will fix this.

**Comment by bcraigie** [comment]
I still see this in K-9 Mail 5.208

![2017-11-27 08 20 55](https://user-images.githubusercontent.com/18425507/33257154-01484238-d34d-11e7-8ff3-43eeac085883.png)

**Comment by philipwhiuk** [comment]
It's fixed in 5.300 and later - you'll need to update / wait for the update to be made available.
