### ISSUE TITLE
Notifications silent on Wear OS 4

### ISSUE THREAD

**Issue by marcelmu** [thunderbird/thunderbird-android#7271]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.603

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Pixel 8 Pro / Pixel Watch 2

### Steps to reproduce

1. Phone and watch paired
2. Receive an email

### Expected behavior

Notification appears as popup on watch with vibration and ringtone

### Actual behavior

Notification appears silent in background (on phone itself it vibrates and rings)

This is the only app where I noticed this behaviour. 

### Logs
[logs.txt](https://github.com/thundernest/k-9/files/13051966/logs.txt)

**Comment by cketti** [comment]
As far as I can tell this is not a bug in K-9 Mail. If the notification has the desired effect on the phone, we have done everything correctly. 
It is up to the app connecting the phone to the watch to correctly transport notifications to the watch. Make sure notifications for K-9 Mail aren't muted in the Pixel Watch app. See https://support.google.com/googlepixelwatch/answer/13532591?hl=en

**Comment by marcelmu** [comment]
Thanks.
So Google Support sends me here, you send me to Google.

It is just odd that only K9 is messed up in the setup

**Comment by cketti** [comment]
If Google can point out what the app needs to do differently, we'd be happy to make the change. But according to the developer documentation they published we're doing everything correctly. And you reported the notification behaves as expected on the phone. There's not much else we can do.

**Comment by marcelmu** [comment]
It just doesn't make sense that it is only not working for K9.

But ok, then I have to live with that

**Comment by marcelmu** [comment]
So I did some debugging and figured something out, @cketti:

`SingleNotifications` are always silent:
https://github.com/thundernest/k-9/blob/main/app/core/src/main/java/com/fsck/k9/notification/SingleMessageNotificationDataCreator.kt#L17

They are then of course sent silently:
https://github.com/thundernest/k-9/blob/main/app/core/src/main/java/com/fsck/k9/notification/NotificationHelper.kt#L114

Having this with `silent=false` obviously triggers the vibration on the watch as expected.

A new Email triggers a silent `SingleNotification` and a non silent `SummarySingleNotification`.
However only the `SingleNotification` gets forwarded to WearOS, not the Summary. 

Unfortunately I'm not able to figure out why as of now

**Comment by marcelmu** [comment]
A debug version with the Single notification not being silent so far behaves as expected.

There are probably some implications I'm not aware of yet

**Comment by cketti** [comment]
We don't want the device to trigger 9 (current max. number of single notifications) notification sounds/vibrations when 9+ new messages are downloaded during a sync. You could try `silent=false` and [`setGroupAlertBehavior()`](https://developer.android.com/reference/androidx/core/app/NotificationCompat.Builder#setGroupAlertBehavior(int)).

**Comment by marcelmu** [comment]
Ah I see, thanks.

The `GroupAlertBehavior` did the trick, though!

Will create a PR if I get around to it.

**Comment by cketti** [comment]
Thanks. It would be helpful to us if you also tested your changes on Android versions that don't support grouped notifications, i.e. versions prior to Android 7.0.

**Comment by marcelmu** [comment]
I was only able to test with a virtual device. Notifications looked fine there.

**Comment by chennin** [comment]
@marcelmu @cketti thank you for this! It fixed a big annoyance I had when I got a Pixel Watch 2.

**Comment by CHILIKE** [comment]
Hi. The same error occurs with the Samsung Galaxy Fit3 device. The message goes through but there is no vibration, i.e. the device receives the signal in silent mode. For all other applications, the device vibrates normally during the notification. Will this be fixed in a new release of K9 Mail?

**Comment by thedgdthe** [comment]
On a Samsung S23 and Galaxy fit 3 same problem, notification received but no vibration. Android 14, k9 6.804.

**Comment by brian6932** [comment]
I can still reproduce this issue on Wear OS 5 + Android 14 + `net.thunderbird.android.beta` `12.0b6` + IMAP4 IDLE/PUSH.
