### ISSUE TITLE
Push notifications won't work after importing the settings from K-9 Mail on Android 15

### ISSUE THREAD

**Issue by pvones** [thunderbird/thunderbird-android#8549]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.1

### Where did you get the app from?

Google Play

### Android version

15

### Device model

Google Pixel 8a

### Steps to reproduce

1. You already use K-9 Mail and IMAP push notifications
2. Install Thunderbird Mobile
3. Import settings from the K-9 Mail
4. Enable access to contacts and notifications
5. Send an email to your email account

### Expected behavior

Push notifications will work as in K-9 Mail

### Actual behavior

Push notifications doesn't work. On Android 15 it didn't display the push notification screen settings **nor asked for the alarms permission**. 

The workaround was to switch the notifications from push to poll and back in the Thunderbird settings. After that it displayed the push notification screen settings and everything works now.

**EDIT** The whole thing is a big mess. When I disabled the Push switch on the Inbox folder and enabled it again, the notification stopped working. The only way was to uninstall Thunderbird and install again. This time I imported the settings from a file (because I already uninstalled the K-9 Mail) and it has **finally asked for the alarms permission**.

Note that the same import steps worked fine on Android 12 device and the push notifications worked immediately as expected.

**Comment by PhoenixIV** [comment]
I do not receive push notifications at all, even when set up manually.
I have K9 and Thunderbird. Both with enabled push notifications on the inbox folder. Both set up manually with the same account.

Push works on K9.
Push does not work on Thunderbird.

**Comment by PhoenixIV** [comment]
Thunderbird v8.0
K-9 v8.1

Thanks for the hint. I just installed Thunderbird from F-Droid. There it is the most recent version. This might already be fixed in 8.1?

Disabling push and enabling it again does not do anything. The same for the sync function (which I have no idea what that is)

**Comment by PhoenixIV** [comment]
> There is something wrong on the recent Android versions.

Damn! This is it!

I was running K-9 on Android 8.1 but Thunderbird on Android 15.

Now I have both apps installed on Android 8.1 and push notifications now work for both. So there is a bug, but limited to newer Android versions.

**Comment by PhoenixIV** [comment]
Just to give as much information as possible: I now updated to Thunderbird 8.1 on Android 15 and could not get push to work - therefore different from what @pvones reports. Thunderbird already has permission to send notifications. New Emails also do not show up (push) when the inbox page is opened / in the foreground.

This issue is mainly about push not working when settings were imported from K-9. For me they do not work at all. So the scope is somewhat different.

**Comment by PhoenixIV** [comment]
Oh my god. Update: Push notifications now do work after I granted Thunderbird permission to "schedule alarms". I explicitly did not want to do that because I saw no need nor connection.

**Comment by pvones** [comment]
Interesting, I don't have the Thunderbird app listed in the special apps setting for alarms, but it works anyway (on Google Pixel).

Android is just a one big mess :-(

**Comment by capitano799** [comment]
Same problem here. 
Thunderbird 8.1 from F-Droid running on Oneplus 6 with lineageOS 21 (Android 14), I've imported my settings from thunderbird desktop. 
Reminders and alarms activated, push is activated for all inbox folders, still I don't get any notification beyond "waiting for new email". Energy saving features of course deactivated. K9 mail worked flawlessly before.

**Comment by carmenTuT** [comment]
After every app update or phone update, push no longer works. Once I have opened the app, it works again. Until the next time. Settings are all as recommended, I don't change anything before or after the updates.

**Comment by HIM049** [comment]
I have same problem there. 
My thunderbider version is 8.1, install form play store. And my Android version is 14, I imported settings form desktop with QR code. 
The thunderbird was asked me for the notification permission, but I wasn't receive any notification. I was tired to find and open alaem permission but I can't find it in permission list.

**Comment by dusscloud** [comment]
Same situation with thunderbird 8.2 on Android 14, settings imported from desktop, and all tips above have been done (push enabled, alarm and reminders granted, etc.)

**Comment by pvones** [comment]
> I was tired to find and open alaem permission but I can't find it in permission list.

That's the problem. Even the permission was set and the push notifications works correctly, Thunderbird isn't listed in the applications with the Alarm permission (Android 15).

**Comment by NewKidOnTheBlock** [comment]
I'm using Thunderbird 8.2 on a Xiaomi Poco phone.
I've set notifications to 15min and waited for an hour, but nothing happened.

Notifications only worked after turning off Energy Saving mode for Thunderbird.

**Comment by cketti** [comment]
It looks like this GitHub issue is about a lot of related, but distinct problems in the app. Since we use this issue tracker to organize work, we need to split this into one GitHub issue per bug/problem.

I believe the problem described in the original report was caused a bug that failed to start the foreground service necessary for Push. This should be fixed in Thunderbird 8.2 (see #8525). People that have the exact problem as the one described by the original report, please test with the that version and report back if this fixes your issue.

For everyone else: Please carefully read the [support page on push](https://support.mozilla.org/en-US/kb/configure-push-email-thunderbird-android) to make sure the app is configured properly. If this still doesn't help, please create a new GitHub issue and (very important) include a [debug log](https://github.com/thunderbird/thunderbird-android/wiki/LoggingErrors) recorded while first enabling airplane mode, then disabling it. That's an easy way to trigger restarting push and should allow us to see if anything goes wrong with starting push on your device.

**Comment by pvones** [comment]
> If this still doesn't help, please create a new GitHub issue and (very important) include a [debug log](https://github.com/thunderbird/thunderbird-android/wiki/LoggingErrors) recorded while first enabling airplane mode, then disabling it. That's an easy way **to trigger restarting push** and should allow us to see if anything goes wrong with starting push on your device.

@cketti This is actually very interesting and useful information, because I always had to use the Force Close option in Settings in order to restart the stuck push. Would be possible to make the restart even easier by an option in the Thunderbird app menu?

The debug log would have to be able to record several hours at least as the push service issues are random and usually reproducible while walking the city only.

**Comment by cketti** [comment]
We're not going to add a way to manually restart push. If it's not working, that's a bug that needs to be fixed, 
not something to be worked around. 
In this case, toggling airplane mode is only used as a trigger to make sure the debug log contains the information we're looking for.

If push is working initially, but stops at some point, that's a completely different issue. In that case we do need a log that includes the moment when push stopped working. Chances are you can't reliably reproduce this condition. So we do need a log that spans several hours. Unfortunately, the app currently doesn't support recording such a log. The only way to log multiple hours of operation is by connecting a computer and using adb to write the system log to a file.

**Comment by pvones** [comment]
> If push is working initially, but stops at some point, that's a completely different issue. In that case we do need a log that includes the moment when push stopped working. 

I tried to record it dozen of times, but even when I managed to catch the moment when it stopped working there was absolutely nothing in the logfile in that time frame. It looked as some buffer wasn't flushed or so.

> The only way to log multiple hours of operation is by connecting a computer and using adb to write the system log to a file.

I know that, but this kind of bug with stuck push service can never be reproduced under ideal conditions when the phone is just sitting at a single location. You need to move in the city, go to subway or by train to have short 5G signal outages in order to reproduce it.

**Comment by HIM049** [comment]
@cketti Actually I'm useing the 8.2 release from play store, and I'm sure about the permissions were given. But I still cannot receive any message push, while the mail app that provided by my ROM is working.

I'm not sure about what could I try or what can I do to help you to fix this problem?

**Comment by PhoenixIV** [comment]
I suggest to add a check and "permission needed" screen for alarms.

**Comment by cketti** [comment]
@HIM049: Please record a debug log and open a new GitHub issue with detailed information on the steps you have performed to configure push.

**Comment by ajay-actuary** [comment]
What fixed for me is:
Settings -> Accounts -> select email account -> notifications -> tick "new mail notifications".  This setting is on by default in K9 but off in Thunderbird. Push notifications work fine after this change.

**Comment by kewisch** [comment]
I'm going to go ahead and close this issue, as cketti mentioned there are a lot of related but distinct problems mentioned here. https://support.mozilla.org/en-US/kb/configure-push-email-thunderbird-android has some details for anyone who hasn't seen it.

We're also looking to implement #8830 which will make the messages more clear.
