### ISSUE TITLE
ACTION_SEND_MULTIPLE only sends one attachment

### ISSUE THREAD

**Issue by santawho** [thunderbird/thunderbird-android#9357]
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

K-9 Mail

### App version

10.0

### Where did you get the app from?

Google Play

### Android version

12

### Device model

POCO X3 NFC

### Steps to reproduce

1. in some other app an Email Intent is produced with the following steps

```
        **intent = new Intent(Intent.ACTION_SEND_MULTIPLE);**
        intent.setType("text/plain");
        final ArrayList<Uri> attachments = new ArrayList<>();
        for (final File logFile : logDir.listFiles())
            attachments.add(FileProvider.getUriForFile(context, context.getPackageName(), logFile));
        **intent.putParcelableArrayListExtra(Intent.EXTRA_STREAM, attachments);**

        intent.putExtra(Intent.EXTRA_EMAIL, new String[] {mailAddress});
        intent.putExtra(Intent.EXTRA_TEXT, report.toString());
        intent.putExtra(Intent.EXTRA_SUBJECT, subject);

        intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);

        context.startActivity(
                Intent.createChooser(intent, intent_chooser_title);

```

The number of entries in the list is about 6

2. Android shows the Chooser to pass the intent to another app
3. choose K9mail
4. K9mail opens Email Editor
5. there is only one of the files as an attachment to the new mail
6. verify with other apps: GMail, WhatsApp, save-files-to-dir ... all working properly with all of the files

### Expected behavior

All of the listed attachments should be added into the new mail editor

### Actual behavior

only one attachment is added.
I assume, the last one in the list, but not sure if always true.

**Comment by kewisch** [comment]
Can you check on beta? We fixed an issue related to this there.

**Comment by santawho** [comment]
I joined the beta program for K9 on Play Store.
I waited to become a beta tester.
I uninstalled the app.
Then installed again from Play Store, which names the app as "K-9 Mail (Beta)"
After installation however it is still showing as Version 10.0.

The mentioned behaviour has not changed.

Is this the right way to install the beta you were asking for ?

**Comment by kewisch** [comment]
You will need to install Thunderbird for Android beta: https://play.google.com/store/apps/details?id=net.thunderbird.android.beta

**Comment by santawho** [comment]
on Thunderbird Beta Version 11.0b2

still the same, only one of the attachments showing at the bottom of the mail editor view

**Comment by kewisch** [comment]
What about https://ftp.mozilla.org/pub/thunderbird-mobile/android/nightly/latest-main/ ? If it says you cannot install please try downloading multiple times, I recently saw some infra issues.

**Comment by santawho** [comment]
installed thunderbird-12.0a1.apk	12M	20-Jun-2025 13:41

confirm: all files show up in this version.

**Comment by mantrasiva** [comment]
> You will need to install Thunderbird for Android beta: https://play.google.com/store/apps/details?id=net.thunderbird.android.beta

hi
i will try , but why can't i download the beta from here and install from here?
may i know the different between the file hosted here and google play?

about:"can't hear and see notification when i send emails " why has been closed because "not planed" ? 
is a feature included in thunderbird & k9
in the account option -> there is 
new mail notificaition
include outgoing mail "show a notification for message i sent" >it doesn't work!

ps i would like to ask a feature to add more colours ,k-9 is brown and thunderbid is blue -but i can't do it
thanks

**Comment by drgerg** [comment]
I also had this problem, and installing Thunderbird Daily 12.0a1 solved it.
Thanks!

**Comment by kewisch** [comment]
Sweet, thanks! Be sure to move back to beta or release though, as daily releases from the apk have no updates. 11.0b4 should include this, and 10.1 with this fix is rolling out at 30% right now.

**Comment by mantrasiva** [comment]
> Sweet, thanks! Be sure to move back to beta or release though, as daily releases from the apk have no updates. 11.0b4 should include this, and 10.1 with this fix is rolling out at 30% right now.

hi
but may i know wht the apk downloaded from here is different with google play apk?
i think it's pretty download from here
thanks
