### ISSUE TITLE
Back button stops working in Inbox after navigating to another folder

### ISSUE THREAD

**Issue by Hawk777** [thunderbird/thunderbird-android#9484]
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

11.0

### Where did you get the app from?

F-Droid

### Android version

16

### Device model

Pixel 9A

### Steps to reproduce

1. Begin with Thunderbird not running (e.g. Force Stopped).
2. Open Thunderbird, arriving in the inbox.
3. Press the Back button. Thunderbird closes.
4. Re-open Thunderbird, arriving in the inbox.
5. Using the folders sidebar, navigate to another folder.
6. Press the Back button twice.

### Expected behavior

The first press of the back button in step 6 should return to the inbox. The second press, being already in the inbox, should close Thunderbird.

### Actual behavior

The first press returns to the inbox. The second press causes the message list to flicker, but remains in the inbox. Subsequent presses do the same; the Home or Recents button must be used to close Thunderbird.

### Logs

This shows navigating from inbox to sent, then pushing back about half a dozen times:

[k9mail-logs.txt](https://github.com/user-attachments/files/21378258/k9mail-logs.txt)

**Comment by GeoffreyAA** [comment]
Same issue on the latest version of K9 and Android 11. Never happened before.

**Comment by assensus** [comment]
I've noticed the same annoying bug on a Galaxy S24+ and Android 15.
Any update on this?

**Comment by krzysdz** [comment]
Sounds like #9407, which should be fixed in beta by #9433.

**Comment by Hawk777** [comment]
It is exactly the same symptoms, and the fixing commit does not appear to be reachable from the `THUNDERBIRD_11_0` tag, so that seems likely. Does this ticket stay open until the release (because it’s not fixed in any official release) or get closed immediately (because the fix has been merged and there is nothing further for devs to do about it)?

**Comment by asoucar** [comment]
Should be fixed by #9433
