### ISSUE TITLE
Font size options are missing

### ISSUE THREAD

**Issue by siffegh** [thunderbird/thunderbird-android#9674]
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

11.1

### Where did you get the app from?

Google Play

### Android version

8 (LG) and 11 (NUU)

### Device model

LG G7 (LM-G710VM) and NUUB10

### Steps to reproduce

Open settings > General settings > Display > look for font size.

### Expected behavior

Font size should appear between Composer theme and Animation.

### Actual behavior

Font size does not appear between Composer theme and Animation - or anywhere else in settings.

### Logs

[k9mail-logs.txt](https://github.com/user-attachments/files/22014326/k9mail-logs.txt)

**Comment by siffegh** [comment]
I've just seen a report that this change was intentional and that text size can be changed in the device's settings. First of all, that setting is where I want it. Second, I increased it to largest and it didn't have any effect on any messages anyway. This change is UNACCEPTABLE. Will go back to Bluemail if not reverted.

**Comment by martinstoeckli** [comment]
The customizeable font size was very helpful to me, at the moment the mail preview content is even smaller than the system font size and barely readable.

Not everything should have the same font size, in this case the mail content is surely more important that e.g. the system menu. 
By using the Android settings for everything, one would have to modify the control size of every app, just to get the mail content readable. This was solved better with the customizeable setting and I hope there is a chance to get it back.

Even a simplified dropdown with relative values like 'normal' > 'large' > 'extra large' would be better than the fixed size.

**Comment by nomis** [comment]
This feature is [still present in the K-9 build of the application](https://github.com/thunderbird/thunderbird-android/blob/main/app-k9mail/src/release/kotlin/app/k9mail/featureflag/K9FeatureFlagFactory.kt), it's just hidden from users of the Thunderbird-branded version.

**Comment by asoucar** [comment]
Thank you for the report. Per @wmontwe 's comment here [on this issue](https://github.com/thunderbird/thunderbird-android/issues/9709#issuecomment-3249281014), the font size redesign is on the table as we redesign the UI. Clearly the message text should be respecting the system font and we will make sure it it addressed

**Comment by rafnov** [comment]
It's so real shame. They were introduced and withdrawn somewhere between newest versions of Thunderbird for Android, while K-9 still has them. If rather have stupid K-9 colours but at least I can configure fonts properly to my sight.
And Thunderbird claims it is former K-9... Shame again.

Sorry, had to breathe.
