### ISSUE TITLE
K-9 v12.0 Crashed on Android 12

### ISSUE THREAD

**Issue by joeyiii57** [thunderbird/thunderbird-android#9737]
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

K-9 Mail

### App version

K-9 Mail V12.0

### Where did you get the app from?

F-Droid

### Android version

12

### Device model

Samsung Galaxy S10e

### Steps to reproduce

After update app crashed on open.  Uninstalled and did clean reinstall.  App crashed on open.

### Expected behavior

duh

### Actual behavior

App crashed

**Comment by huck-g** [comment]
Same here with Android 11.

**Comment by garrettboone** [comment]
LineageOS 22.1

logcat when app crashes... the individual accounts update but then unified seems to crash.
```
09-06 19:38:56.346 29842 29842 I ImeTracker: com.fsck.k9:15eec511: onRequestHide at ORIGIN_CLIENT reason HIDE_SOFT_INPUT fromUser false
09-06 19:38:56.347 29842 29842 I ImeTracker: com.fsck.k9:15eec511: onFailed at PHASE_CLIENT_VIEW_SERVED
09-06 19:38:56.353 29842 29842 D AutofillManager: view not autofillable - not passing ime action check
09-06 19:38:56.365 29842 29842 E ExceptionHandler: UncaughtException
09-06 19:38:56.368 29842 29842 E AndroidRuntime: FATAL EXCEPTION: main
09-06 19:38:56.368 29842 29842 E AndroidRuntime: Process: com.fsck.k9, PID: 29842
09-06 19:38:56.368 29842 29842 E AndroidRuntime: java.lang.IllegalStateException: Account not found: unified_account
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at app.k9mail.legacy.ui.folder.DefaultDisplayFolderRepository.getDisplayFoldersFlow(DefaultDisplayFolderRepository.kt:89)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at net.thunderbird.feature.navigation.drawer.siderail.domain.usecase.GetDisplayFoldersForAccount.invoke(GetDisplayFoldersForAccount.kt:20)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at net.thunderbird.feature.navigation.drawer.siderail.ui.DrawerViewModel$loadFolders$$inlined$flatMapLatest$1.invokeSuspend(Merge.kt:190)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at net.thunderbird.feature.navigation.drawer.siderail.ui.DrawerViewModel$loadFolders$$inlined$flatMapLatest$1.invoke(Merge.kt:0)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at net.thunderbird.feature.navigation.drawer.siderail.ui.DrawerViewModel$loadFolders$$inlined$flatMapLatest$1.invoke(Merge.kt:0)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:30)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt:0)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt:0)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:20)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:360)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:134)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:53)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:44)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1.emit(Merge.kt:29)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at kotlinx.coroutines.flow.DistinctFlowImpl$collect$2.emit(Distinct.kt:73)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at kotlinx.coroutines.flow.FlowKt__TransformKt$filterNotNull$$inlined$unsafeTransform$1$2.emit(Emitters.kt:50)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at net.thunderbird.feature.navigation.drawer.siderail.ui.DrawerViewModel$loadFolders$$inlined$map$1$2.emit(Emitters.kt:50)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:401)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at kotlinx.coroutines.flow.StateFlowImpl$collect$1.invokeSuspend(StateFlow.kt:0)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:237)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:175)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:147)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:470)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$kotlinx_coroutines_core(CancellableContinuationImpl.kt:504)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$kotlinx_coroutines_core$default(CancellableContinuationImpl.kt:493)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:359)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at kotlinx.coroutines.flow.StateFlowSlot.makePending(StateFlow.kt:290)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at kotlinx.coroutines.flow.StateFlowImpl.updateState(StateFlow.kt:354)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at kotlinx.coroutines.flow.StateFlowImpl.compareAndSet(StateFlow.kt:324)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at app.k9mail.core.ui.compose.common.mvi.BaseViewModel.updateState(BaseViewModel.kt:233)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at net.thunderbird.feature.navigation.drawer.siderail.ui.DrawerViewModel.selectAccount(DrawerViewModel.kt:128)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at net.thunderbird.feature.navigation.drawer.siderail.ui.DrawerViewModel.event(DrawerViewModel.kt:103)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at net.thunderbird.feature.navigation.drawer.siderail.ui.DrawerViewModel.event(DrawerViewModel.kt:23)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at net.thunderbird.feature.navigation.drawer.siderail.ui.DrawerViewKt$DrawerView$$inlined$observe$1.invoke(UnidirectionalViewModel.kt:91)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at net.thunderbird.feature.navigation.drawer.siderail.ui.DrawerViewKt$DrawerView$$inlined$observe$1.invoke(UnidirectionalViewModel.kt:91)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at net.thunderbird.feature.navigation.drawer.siderail.ui.DrawerViewKt$DrawerView$2$1.invokeSuspend(DrawerView.kt:37)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:79)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:991)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8934)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
09-06 19:38:56.368 29842 29842 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d5156f5, Dispatchers.Main.immediate]
```

**Comment by garrettboone** [comment]
#9735

**Comment by Wohlstand** [comment]
On Android 10 (Galaxy Note 9) it also crashing, just on startup.

**Comment by mwat56** [comment]
Android 13 tablet: crash on start

**Comment by grelkin** [comment]
Android 15: If there are multiple email accounts configured, the app will crash during start-up.

**Comment by ir42-fairphone** [comment]
Same here on Android 14/e-OS 3.1.1 (Fairphone 4) since the last update this night, K9mail crashed every time on start, also after a reboot.

**Comment by carlbennett** [comment]
It's crashing for me after the update. Android 15 (BP1A.250305.020). Google Pixel 9 Pro XL. Installed from F-Droid

**Comment by BITS-Editor** [comment]
Same here, Android 14, Samsung XCover 5 EE.

**Comment by tstelzle** [comment]
Same here on Android12

**Comment by pelmato** [comment]
Same here. According to the changelog, the problem seems to be already fixed in version 12.1 which has not yet reached the FDroid repo...

**Comment by vanicat** [comment]
I believe I have the same problem.

The only way to start it with no crash is to click on the " write a new message" icon in the widget. It will crash anytime when I open the unified inbox.

**Comment by ruckel** [comment]
> The only way to start it with no crash is to click on the " write a new message" icon in the widget.

Thank you! You just saved me from having reconfigure a dozen email accounts. I should do my backup now...

**Comment by bfrucha** [comment]
The app crashes on startup for me too with the new update. I removed all data and reconfigured one email address, which works. As soon as I configure a second one, the app crashes and then crashes repeatedly on startup. I tried reinstalling but the issue remains the same. I'm on Android 12

**Comment by selukov** [comment]
Android 15 K-9 v12.0

I updated the K-9 Mail app to version 12 and it broke - you open it and it immediately crashes.
I reinstalled it and had to set up all the email settings again - IMAP and POP3. It works with one email client, but if you add a second one, the app breaks. It doesn't matter what order or which client - personal, corporate, Yandex, Google. As soon as you add a second email account, the app stops working.

**Comment by hb9eue** [comment]
Same here, fairphone 4, Android 13. Please re publish previous version via fdroid

**Comment by marbx** [comment]
K-9 12.0 from F-Droid crashes when opened on LineageOS 22.2 (Android 15)

I have only 1 account.

I can open K-9 after reading here, added a widget, via the widget.

**Comment by GioPan04** [comment]
Same issue here on Android 16.
```
java.lang.IllegalStateException: Account not found: unified_account
```

**Comment by CecileGallioz** [comment]
Same here on android 13 with two account

**Comment by mikhirev** [comment]
Same here.

```
type: crash
osVersion: google/sunfish/sunfish:13/TQ3A.230805.001.S2/2025012701:user/release-keys
package: com.fsck.k9:39027
process: com.fsck.k9
processUptime: 1665 + 340 ms
installer: org.fdroid.fdroid

java.lang.IllegalStateException: Account not found: unified_account
	at app.k9mail.legacy.ui.folder.DefaultDisplayFolderRepository.getDisplayFoldersFlow(DefaultDisplayFolderRepository.kt:89)
	at net.thunderbird.feature.navigation.drawer.siderail.domain.usecase.GetDisplayFoldersForAccount.invoke(GetDisplayFoldersForAccount.kt:20)
	at net.thunderbird.feature.navigation.drawer.siderail.ui.DrawerViewModel$loadFolders$$inlined$flatMapLatest$1.invokeSuspend(Merge.kt:190)
	at net.thunderbird.feature.navigation.drawer.siderail.ui.DrawerViewModel$loadFolders$$inlined$flatMapLatest$1.invoke(Merge.kt:0)
	at net.thunderbird.feature.navigation.drawer.siderail.ui.DrawerViewModel$loadFolders$$inlined$flatMapLatest$1.invoke(Merge.kt:0)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:30)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt:0)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt:0)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:20)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:360)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:134)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:53)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:44)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1.emit(Merge.kt:29)
	at kotlinx.coroutines.flow.DistinctFlowImpl$collect$2.emit(Distinct.kt:73)
	at kotlinx.coroutines.flow.FlowKt__TransformKt$filterNotNull$$inlined$unsafeTransform$1$2.emit(Emitters.kt:50)
	at net.thunderbird.feature.navigation.drawer.siderail.ui.DrawerViewModel$loadFolders$$inlined$map$1$2.emit(Emitters.kt:50)
	at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:401)
	at kotlinx.coroutines.flow.StateFlowImpl$collect$1.invokeSuspend(StateFlow.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:237)
	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:175)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:147)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:470)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$kotlinx_coroutines_core(CancellableContinuationImpl.kt:504)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$kotlinx_coroutines_core$default(CancellableContinuationImpl.kt:493)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:359)
	at kotlinx.coroutines.flow.StateFlowSlot.makePending(StateFlow.kt:290)
	at kotlinx.coroutines.flow.StateFlowImpl.updateState(StateFlow.kt:354)
	at kotlinx.coroutines.flow.StateFlowImpl.compareAndSet(StateFlow.kt:324)
	at app.k9mail.core.ui.compose.common.mvi.BaseViewModel.updateState(BaseViewModel.kt:233)
	at net.thunderbird.feature.navigation.drawer.siderail.ui.DrawerViewModel.selectAccount(DrawerViewModel.kt:128)
	at net.thunderbird.feature.navigation.drawer.siderail.ui.DrawerViewModel.event(DrawerViewModel.kt:103)
	at net.thunderbird.feature.navigation.drawer.siderail.ui.DrawerViewModel.event(DrawerViewModel.kt:23)
	at net.thunderbird.feature.navigation.drawer.siderail.ui.DrawerViewKt$DrawerView$$inlined$observe$1.invoke(UnidirectionalViewModel.kt:91)
	at net.thunderbird.feature.navigation.drawer.siderail.ui.DrawerViewKt$DrawerView$$inlined$observe$1.invoke(UnidirectionalViewModel.kt:91)
	at net.thunderbird.feature.navigation.drawer.siderail.ui.DrawerViewKt$DrawerView$2$1.invokeSuspend(DrawerView.kt:37)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:79)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@888d87a, Dispatchers.Main.immediate]

```

**Comment by ThiloKaiser** [comment]
I just upgraded and had the app crash on opening.

I uninstalled and re-installed.

I use four email accounts.

As I re-entered all the server info and tested the invidual accounts, eveything worked fine, until I tried the UNIFIED view, from there it crashed and I had to uninstall again.

Cheers

**Comment by lmoellendorf** [comment]
I can confirm K-9 v12.0 crashes immediately when opening unified mailbox. 

Workaround:

Use My Account widget which will open one specific account's maibox(es) only.

Lineage OS 22.2-20250831-NIGHTLY-kiev
Android 15

**Comment by sir-paddy** [comment]
Just updated via F-Droid. App instantly crashes on startup:
- K-9 v12
- Android 16
- Google Pixel 8

Can confirm that opening the app via account widget works. Switching to unified view leads to a crash.

**Comment by AlekseiKhatkevich** [comment]
Same on 2 different phones , Android 15,  LineageOS

**Comment by licaon-kter** [comment]
duplicate https://github.com/thunderbird/thunderbird-android/issues/9711

**Comment by ulph0** [comment]
same here, lineageos 18.1, android11 with f-droid version - can't install as download by hand over it.
update: i read aboye and installed a widget and now i am at least able to open my single account. please be careful wih versions you roll out over f-droid.

**Comment by el-seppo** [comment]
Same here. Crashes aswell as soon as it's starting.
Android 16 / Google Pixel 7a
GrapheneOS
Installed on f-droid

**Comment by Kramarbeiter** [comment]
Same here

**Comment by BonifacioCalindoro** [comment]
Same here

Android 13 TKQ1.221114.001
Xiaomi HyperOS 1.0.12.0.TKCEUXM
Xiaomi Redmi note 11 pro 5G

**Comment by BonifacioCalindoro** [comment]
> I can confirm K-9 v12.0 crashes immediately when opening unified mailbox. 
> 
> Workaround:
> 
> Use My Account widget which will open one specific account's maibox(es) only.
> 
> Lineage OS 22.2-20250831-NIGHTLY-kiev
> Android 15


This worked for me, the thing that crashes is opening the "unified inbox"

**Comment by jessienab** [comment]
> I believe I have the same problem.
> 
> The only way to start it with no crash is to click on the " write a new message" icon in the widget. It will crash anytime when I open the unified inbox.

Temporary fix per above: 

* Add "message list" widget to home screen
* Tap on the pencil to write a new email
* press back button arrow IN app
* open side menu, settings (gear icon)
* general settings > display > Account list > uncheck "Show unified account"

**Comment by dav1138** [comment]
Updated to version 12 using F-Droid. App crashes on startup.

Android 16 / Pixel 8
GrapheneOS

Also confirming access to inbox through widget works, but switching to unified crashes.

`java.lang.IllegalStateException: Account not found: unified_account`

**Comment by pbielefeldt** [comment]
Thanks @jessienab, you just saved my day!

---

BTW: Fairphone 5, Stock Android 15 is also affected.

**Comment by PeaceOutMan** [comment]
V12 crashes on open app.  Unable to resolve.  

Android 15 Device

**Comment by lefablab** [comment]
Same bug with e/OS v3.0.4 on Fairphone 3, K-9 v12
I am using the e/OS Mail application while waiting for the bug to be fixed.

**Comment by Knollingar** [comment]
K9 Crashed on Fairphone 4
installed from F-Droid

**Comment by white-gecko** [comment]
Does a downgrade to 11.1 fix the issue?

Unfortunately an update to 12.1 packages from github release https://github.com/thunderbird/thunderbird-android/releases/tag/K9MAIL_12_1 does not work, if the f-droid package is installed, since they are signed with different keys.

The issue is also documented in the f-droid forum: https://forum.f-droid.org/t/k9-email-app-not-work-after-updated-to-v-12-00/33225

The solution is patience.

**Comment by git-developer** [comment]
Another workaround (well, sort of) until K-9 12.1 is released:
Install Thunderbird 11.1, Import Settings from K-9, use Thunderbird

**Comment by europrimus** [comment]
Thanks to [jessienab](https://github.com/thunderbird/thunderbird-android/issues/9737#issuecomment-3263800577) for the workaround.

I have the same issue with K-9 mail V12, installed from f-droid, on a Google pixel 3 under Android 14 ( Calyxos 5.17.1 )
k-9 mail display notification fine and allow respond.
But when launch to view _unified account_ it crash.

**Comment by adamthiede** [comment]
> > I believe I have the same problem.
> > The only way to start it with no crash is to click on the " write a new message" icon in the widget. It will crash anytime when I open the unified inbox.
> 
> Temporary fix per above:
> 
>     * Add "message list" widget to home screen
> 
>     * Tap on the pencil to write a new email
> 
>     * press back button arrow IN app
> 
>     * open side menu, settings (gear icon)
> 
>     * general settings > display > Account list > uncheck "Show unified account"

You are awesome! My mom says thanks. This got her phone working again.

**Comment by ingerling** [comment]
> 
> Temporary fix per above:
> 
>     * Add "message list" widget to home screen
> 
>     * Tap on the pencil to write a new email
> 
>     * press back button arrow IN app
> 
>     * open side menu, settings (gear icon)
> 
>     * general settings > display > Account list > uncheck "Show unified account"

Thank you! 
For some reason the widget wasn't working for me (may be cause I emptied the cache). 

Another possible start for this workaround: use share with k9

**Comment by el-seppo** [comment]
> > I believe I have the same problem.
> > The only way to start it with no crash is to click on the " write a new message" icon in the widget. It will crash anytime when I open the unified inbox.
> 
> Temporary fix per above:
> 
> * Add "message list" widget to home screen
> * Tap on the pencil to write a new email
> * press back button arrow IN app
> * open side menu, settings (gear icon)
> * general settings > display > Account list > uncheck "Show unified account"

Thanks mate.
That helps me a lot! I can't downgrade the app, because if a missing package error for some strange reason. so that's my only way.

**Comment by licaon-kter** [comment]
@white-gecko the solution is to disable unified inbox, see the posts above

**Comment by isnikulin** [comment]
> @white-gecko the solution is to disable unified inbox, see the posts above

That is literally the only feature i use k9 for. Not a solution but a workaround.

**Comment by pbielefeldt** [comment]
Thank you, @joeyiii57, for reporting this issue. By now, it appears evident that a lot of people are affected, on many different OS. Also, it seems likely the unified account is the cause for the behavior. May I suggest you update the title of this issue to reflect that? I propose "v12.0 Crashes when showing unified_account".

Also, as mentioned before, this is a duplicate of #9711. Not sure you have the privileges of marking it as such, though.

**Comment by jdhoek** [comment]
@joeyiii57 In addition to editing the title as @pbielefeldt suggests, perhaps link (or copy) the [workaround](https://github.com/thunderbird/thunderbird-android/issues/9737#issuecomment-3263800577) @jessienab helpfully figured out in the first post as well. This issue seems likely to get a lot of people wandering in.

**Comment by zwolowz** [comment]
Was just able to download 12.1 from F-Droid which fixed the issue.

**Comment by jdhoek** [comment]
@zwolowz The changelog lists this bug, and re-enabling the unified inbox works for me.

The workaround mentioned in this issue is no longer needed with version 12.1.

**Comment by Wohlstand** [comment]
Can anybody close this issue since it's completed now?

**Comment by wmontwe** [comment]
**v12.1** with the fix is released at https://f-droid.org/de/packages/com.fsck.k9/, see #9711
